/* Padding */ OP_DROP
/* P2SH */ OP_DUP OP_SHA256 <0xc3f02727de3c5aa4f2e830d5e05d14a941218755d2c10a34c19c1202c9f19c45> OP_EQUALVERIFY <0x01> OP_DEFINE 

//Verify starting from 0
OP_6 OP_PICK <> OP_EQUALVERIFY
OP_4 OP_PICK <> OP_EQUALVERIFY
OP_3 OP_PICK <> OP_EQUALVERIFY

OP_INPUTINDEX OP_1ADD OP_INPUTBYTECODE
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop start
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop end
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop continuation_y
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop continuation_x
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop signature_r
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop u2
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop u1
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF OP_NIP //drop inverses
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF //keep tableQ
<1> OP_SPLIT OP_SWAP OP_DUP <0x4d> OP_EQUAL OP_IF OP_DROP <2> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_DUP <0x4e> OP_EQUAL OP_IF OP_DROP <4> OP_SPLIT OP_SWAP OP_BIN2NUM OP_SPLIT OP_ELSE OP_BIN2NUM OP_SPLIT OP_ENDIF OP_ENDIF //keep tableG
OP_DROP OP_2SWAP

<115792089210356248762697446949407573529996955224135760342422259061068512044369> //CURVE.N

//DER: 0x30 <len> 0x02 <lenR> <rBytes> 0x02 <lenS> <sBytes>
OP_SWAP <1> OP_SPLIT OP_NIP <1> OP_SPLIT OP_SWAP OP_SPLIT OP_SWAP //sighash, restDER
<1> OP_SPLIT OP_NIP <1> OP_SPLIT OP_SWAP OP_SPLIT //r, restDER
<1> OP_SPLIT OP_NIP <1> OP_SPLIT OP_SWAP OP_SPLIT OP_DROP //sighash, r(BE), s(BE)
OP_REVERSEBYTES OP_SIZE OP_1SUB OP_SPLIT OP_DUP <0x00> OP_CAT OP_BIN2NUM <0x8000> OP_GREATERTHAN OP_IF <0x00> OP_CAT OP_ENDIF OP_CAT
OP_SWAP
OP_REVERSEBYTES OP_SIZE OP_1SUB OP_SPLIT OP_DUP <0x00> OP_CAT OP_BIN2NUM <0x8000> OP_GREATERTHAN OP_IF <0x00> OP_CAT OP_ENDIF OP_CAT
OP_DUP OP_TOALTSTACK //Store R
OP_SWAP

// w = sInv
    //Verify s inverse ((s * sInv) % p === 1)
    OP_4 OP_ROLL //sInv
    OP_SWAP //s
    OP_OVER //sInv
    OP_MUL //(s * sInv)
        OP_4 OP_PICK OP_MOD
    OP_1 OP_EQUALVERIFY //(s * sInv) % p === 1

//z = msgHash
OP_ROT transaction_serialization
// OP_ROT OP_DROP <0xddac4895627490c28cdbd23936b5ebd9c6b7d5359bdb85d52021a01f7b2f9759>
OP_REVERSEBYTES OP_SIZE OP_1SUB OP_SPLIT OP_DUP <0x00> OP_CAT OP_BIN2NUM <0x8000> OP_GREATERTHAN OP_IF <0x00> OP_CAT OP_ENDIF OP_CAT

//u1 ≡ z*w(modn)
OP_OVER 
OP_MUL
    OP_3 OP_PICK 
    OP_TUCK OP_MOD OP_DUP OP_0 OP_LESSTHAN OP_IF OP_ADD OP_ELSE OP_NIP OP_ENDIF
OP_DUP OP_TOALTSTACK

// u2 ≡ r*w (modn)
OP_ROT OP_ROT OP_MUL
    OP_2 OP_ROLL OP_TUCK OP_MOD OP_DUP OP_0 OP_LESSTHAN OP_IF OP_ADD OP_ELSE OP_NIP OP_ENDIF
OP_DUP OP_TOALTSTACK

// store end index
OP_DEPTH OP_2 OP_SUB OP_PICK OP_TOALTSTACK

OP_SWAP

/* Param */ <$(table_q_hash)> //Table Hash
/* Param */ <$(table_g_hash)> //Table Hash

// /* Invocation */
<0x01> OP_INVOKE

// /* Covenant */
OP_DEPTH OP_2 OP_EQUALVERIFY //Verify result Y,X
OP_FROMALTSTACK OP_1SUB OP_SIZE <0x04> OP_INVOKE OP_SWAP OP_CAT
<0x00> 
OP_CAT
OP_ROT OP_SIZE <0x04> OP_INVOKE OP_SWAP OP_CAT //push continuation_y
OP_CAT
OP_SWAP OP_SIZE <0x04> OP_INVOKE OP_SWAP OP_CAT //push continuation_x
OP_CAT
OP_FROMALTSTACK OP_SIZE <0x04> OP_INVOKE OP_SWAP OP_CAT //push u2
OP_CAT
OP_FROMALTSTACK OP_SIZE <0x04> OP_INVOKE OP_SWAP OP_CAT //push u1
OP_CAT 
OP_FROMALTSTACK OP_SIZE <0x04> OP_INVOKE OP_SWAP OP_CAT //push r
OP_CAT //expected head of second unlocking script

OP_SIZE <1> OP_INPUTBYTECODE OP_SWAP OP_SPLIT OP_DROP //actual head of second unlocking script
OP_EQUALVERIFY //verify second script verifies rest of computation
<1> OP_UTXOBYTECODE <affine_verify_chain_final> OP_EQUALVERIFY //Verify second script is locked appropriately

OP_1